# ------------------------------------------------------------------------------


- name: Install
  ansible.builtin.shell: |
    curl https://get.volta.sh | bash -s -- --skip-setup
  args: {warn: false} 
  register: task
  changed_when: "'already installed' not in task.stderr"


# ------------------------------------------------------------------------------
# Bash


- name: "bash : Add block to {{ bash_profile_middle }}"
  ansible.builtin.blockinfile:
    path: "{{ bash_profile_middle }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export VOLTA_HOME=$HOME/.volta
      export PATH=$VOLTA_HOME/bin:$PATH

- name: "bash : Create ~/.local/share/bash-completion/completions"
  ansible.builtin.shell: |
    mkdir -p ~/.local/share/bash-completion/completions
  args: {warn: false} 
  changed_when: false

# See <https://docs.volta.sh/reference/completions>.
- name: "bash : Create ~/.local/share/bash-completion/completions/volta.bash"
  ansible.builtin.shell: |
    export VOLTA_HOME=$HOME/.volta
    export PATH=$VOLTA_HOME/bin:$PATH
    volta completions --force --output $HOME/.local/share/bash-completion/completions/volta.bash bash
  changed_when: false


# ------------------------------------------------------------------------------
# Zsh


- name: "zsh : Add block to {{ zsh_zprofile_middle }}"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile_middle }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export VOLTA_HOME=$HOME/.volta
      path=($VOLTA_HOME/bin $path)

- name: "zsh : Create /usr/local/share/zsh/site-functions"
  ansible.builtin.shell: |
    mkdir -p /usr/local/share/zsh/site-functions
  args: {warn: false}
  changed_when: false
  become: true

# See <https://docs.volta.sh/reference/completions>.
- name: "zsh : Create /usr/local/share/zsh/site-functions/_volta"
  ansible.builtin.shell: |
    export VOLTA_HOME={{ ansible_env.HOME }}/.volta
    export PATH=$VOLTA_HOME/bin:$PATH
    volta completions --force --output /usr/local/share/zsh/site-functions/_volta zsh
  changed_when: false
  become: true


# ------------------------------------------------------------------------------


# See <https://docs.volta.sh/guide/understanding>.
- name: Install and set node@16.12.0 as default
  ansible.builtin.shell: |
    export VOLTA_HOME=~/.volta
    export PATH=$VOLTA_HOME/bin:$PATH
    volta install node@16.12.0
  changed_when: false


# ------------------------------------------------------------------------------
